const config = {
  abbreviations: {
    keys: {
      pagePath: 'pp',
      subdomain: 'sd',
      sessionCount: 'sc',
      ipAddress: 'ip',
      referrer: 'ref',
      firstVisitDate: 'fvd',
      cta: 'cta',
      clickPath: 'cp',
      uniqueVisitorId: 'uvid',
      browser: 'br',
      device: 'dv',
      pageCount: 'pc',
      landingPage: 'lp',
      utm_source: 'us',
      utm_medium: 'um',
      utm_campaign: 'uc',
      utm_content: 'uct',
      utm_term: 'ut',
      ms: 'ms',
    },
    values: {
      Chrome: 'Ch',
      Firefox: 'FF',
      Safari: 'SF',
      Edge: 'Ed',
      Opera: 'Op',
      IE: 'IE',
      google: 'G',
      facebook: 'Fb',
      twitter: 'Tw',
      LinkedIn: 'Li',
      email: 'em',
      social: 'so',
    },
  },
  urlParams: ['utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term', 'ms', 'aud_cta', 'aud_path'],
  domain: '.audubon.org',
  sessionCookieName: 'aud_sv',
  firstVisitCookieName: 'aud_fv',
  sessionExpiration: 30, // in minutes
};

export default config;
